library(knitr)

percentis_for_metric <- function(metric, filename) {
  metrics = read.table(filename)
  percentis = quantile(metrics[, c(metric)], c(.01, .05, .10, .25, .50, .75, .90, .95, .99))
  return(percentis)
}

metrics_percentis <- function(filename) {
  accm = percentis_for_metric("accm", filename)
  acc = percentis_for_metric("acc", filename)
  amloc = percentis_for_metric("amloc", filename)
  anpm = percentis_for_metric("anpm", filename)
  an = percentis_for_metric("an", filename)
  asom = percentis_for_metric("asom", filename)
  auv = percentis_for_metric("auv", filename)
  bd = percentis_for_metric("bd", filename)
  bf = percentis_for_metric("bf", filename)
  cbo = percentis_for_metric("cbo", filename)
  da = percentis_for_metric("da", filename)
  dbz = percentis_for_metric("dbz", filename)
  df = percentis_for_metric("df", filename)
  dit = percentis_for_metric("dit", filename)
  dnp = percentis_for_metric("dnp", filename)
  dupv = percentis_for_metric("dupv", filename)
  fgbo = percentis_for_metric("fgbo", filename)
  lcom4 = percentis_for_metric("lcom4", filename)
  loc = percentis_for_metric("loc", filename)
  mlk = percentis_for_metric("mlk", filename)
  mmloc = percentis_for_metric("mmloc", filename)
  noa = percentis_for_metric("noa", filename)
  noc = percentis_for_metric("noc", filename)
  noc = percentis_for_metric("noc", filename)
  nom = percentis_for_metric("nom", filename)
  npa = percentis_for_metric("npa", filename)
  npm = percentis_for_metric("npm", filename)
  obaa = percentis_for_metric("obaa", filename)
  osf = percentis_for_metric("osf", filename)
  pitfc = percentis_for_metric("pitfc", filename)
  rfc = percentis_for_metric("rfc", filename)
  rogu = percentis_for_metric("rogu", filename)
  rsva = percentis_for_metric("rsva", filename)
  sc = percentis_for_metric("sc", filename)
  saigv = percentis_for_metric("saigv", filename)
  uaf = percentis_for_metric("uaf", filename)
  ua = percentis_for_metric("ua", filename)
  uav = percentis_for_metric("uav", filename)
  table = data.frame(acc, accm, amloc, an, anpm, asom, auv, bd, bf, cbo, da, dbz, df, dit, dnp, dupv, fgbo, lcom4, loc, mlk, mmloc, noa, noc, nom, npa, npm, obaa, osf, pitfc, rfc, rogu, rsva, saigv, sc, ua, uaf, uav)
  return(table)
}

all_percentis_by_project <- function(metric) {
  accessanalysis = percentis_for_metric(metric, "dataset/PAPERS/accessanalysis/AccessAnalysis-1.2-src.analizo.metrics.dat")
  bakarali = percentis_for_metric(metric, "dataset/PAPERS/bakar-ali/bakar-dev-20160415-002013.analizo.metrics.dat")
  errorprone = percentis_for_metric(metric, "dataset/PAPERS/error-prone/error-prone-2.0.9.analizo.metrics.dat")
  indus = percentis_for_metric(metric, "dataset/PAPERS/indus/indus.staticanalyses.analizo.metrics.dat")
  inputtracer = percentis_for_metric(metric, "dataset/PAPERS/inputtracer/valgrind-inputtracer.analizo.metrics.dat")
  jastadd = percentis_for_metric(metric, "dataset/PAPERS/jastadd/jastadd2-src.analizo.metrics.dat")
  sourcemeter = percentis_for_metric(metric, "dataset/PAPERS/source-meter/SonarQube-plug-in-master.analizo.metrics.dat")
  srcml = percentis_for_metric(metric, "dataset/PAPERS/srcml/srcML-src.analizo.metrics.dat")
  tacle = percentis_for_metric(metric, "dataset/PAPERS/tacle/tacle_1_2_1_src.analizo.metrics.dat")
  wala = percentis_for_metric(metric, "dataset/PAPERS/wala/WALA-R_1.3.8.analizo.metrics.dat")
  table = data.frame(accessanalysis, bakarali, errorprone, indus, inputtracer, jastadd, sourcemeter, srcml, tacle, wala)
  return(table)
}

knit("qualificacao.Rtex")
