#!/usr/bin/perl
use strict;

if ($ARGV[0] ne '-o' || length($ARGV[1]) == 0) {
  warn "E: missing options!";
  print "Usage: $0 -o <file>\n";
  exit 1;
}

my $filename = $ARGV[1];

my @INCLUIDOS = ();
my @EXCLUIDOS = ();

my @SCAM_PAPERS = `find "SCAM Papers/" -iname *.pdf | sort`;
my @ASE_PAPERS = `find "ASE Papers/" -iname *.pdf | sort`;

foreach my $paper (@SCAM_PAPERS, @ASE_PAPERS) {
  chomp $paper;
  my $PAPER_CONTENT = `pdftotext "$paper" -`;
  print ".";
  if (
       grep(/tool|framework/i, $PAPER_CONTENT) &&
       grep(/download|available/i, $PAPER_CONTENT) &&
       grep(/http|ftp/i, $PAPER_CONTENT) &&
       grep(/static analysis|parser/i, $PAPER_CONTENT)
     ) {
    push @INCLUIDOS, $paper;
  }
  else {
    push @EXCLUIDOS, $paper;
  }
}
print "\n";

open my $FILE, '>', $filename;

print $FILE "TOTAL SCAM = ", scalar(@SCAM_PAPERS), "\n";
print $FILE "TOTAL ASE = ", scalar(@ASE_PAPERS), "\n";
print $FILE "INCLUIDOS = ", scalar(@INCLUIDOS), "\n";
print $FILE "EXCLUIDOS = ", scalar(@EXCLUIDOS), "\n";

print $FILE "### INCLUIDOS ###\n";
$" = "\n";
print $FILE "@INCLUIDOS\n";

close $FILE;
